[package]
name = "geneie"
version = "1.0.0"
edition = "2021"
description = "A desktop plasmid editor"
authors = ["dl-li"]
license = "ISC"

[lib]
name = "geneie_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "sync", "macros"] }
geneie-core = { path = "../backend/geneie-core" }
log = "0.4"
