"""File I/O — parse & write .gbk, .dna, .fasta.

Primers and user data stored as native GenBank features (primer_bind +
misc_feature). Enzymes are recomputed by the plugin, not persisted.
100% round-trip fidelity for all user-editable data.
"""
from __future__ import annotations
from pathlib import Path
from .models import ProjectData, Feature, Primer, PrimerMismatchFeature, BindingSite, Enzyme


# ═══════════════════════════════════════════════════════════════
#  Parse
# ═══════════════════════════════════════════════════════════════

def parse_gbk(path: Path) -> ProjectData:
    from Bio import SeqIO

    record = SeqIO.read(str(path), "genbank")
    features: list[Feature] = []
    primers: list[Primer] = []

    for f in record.features:
        qual = f.qualifiers

        # ── primers ──
        if f.type == "primer_bind":
            primers.append(_parse_primer_feature(f))
            continue

        if f.type == "source":
            continue

        label = qual.get("label", [""])[0] or qual.get("gene", [""])[0] or f.type
        loc = f.location

        if hasattr(loc, "parts") and len(loc.parts) > 1:
            segs = [{"start": int(p.start), "end": int(p.end) - 1} for p in loc.parts]
            start = min(s["start"] for s in segs)
            end = max(s["end"] for s in segs)
        else:
            start = int(loc.start)
            end = int(loc.end) - 1
            segs = []

        color = (
            qual.get("ApEinfo_fwdcolor", [""])[0]
            or qual.get("geneie_color", [""])[0]
            or _default_color(f.type)
        )
        translation = qual.get("translation", [""])[0]

        features.append(Feature(
            id=f"{label}_{start}",
            name=label,
            start=start,
            end=end,
            color=color,
            ftype=f.type,
            segments=segs,
            notes="; ".join(qual.get("note", [])),
            translation=translation,
        ))

    topology = "circular" if "circular" in (record.annotations.get("topology", "") or "") else "linear"
    return ProjectData(
        sequence=str(record.seq).upper(),
        length=len(record.seq),
        topology=topology,
        features=features,
        primers=primers,
        enzymes=[],  # recomputed by plugin
    )


def parse_dna(path: Path) -> ProjectData:
    try:
        import snapgene_reader
    except ImportError:
        raise ImportError("snapgene-reader is required to parse .dna files")

    data = snapgene_reader.snapgene_file_to_dict(str(path))
    seq = data.get("seq", "").upper() if isinstance(data.get("seq"), str) else ""
    features: list[Feature] = []
    for f in data.get("features", []):
        start = f.get("start", 0)
        end = f.get("end", start)
        qual = f.get("qualifiers", {})
        name = qual.get("label", qual.get("gene", f.get("type", "feature")))
        color = qual.get("ApEinfo_fwdcolor", qual.get("geneie_color", _default_color(f.get("type", ""))))
        translation = qual.get("translation", "")
        features.append(Feature(
            id=f"{name}_{start}", name=str(name), start=start,
            end=end - 1 if end > start else start, color=str(color),
            ftype=str(f.get("type", "")), notes=str(qual.get("note", "")),
            translation=str(translation),
        ))
    return ProjectData(
        sequence=seq, length=len(seq),
        topology=data.get("topology", "circular"), features=features,
    )


def parse_fasta(path: Path) -> ProjectData:
    from Bio import SeqIO
    record = SeqIO.read(str(path), "fasta")
    return ProjectData(
        sequence=str(record.seq).upper(),
        length=len(record.seq), topology="linear",
    )


def parse_file(path: Path) -> ProjectData:
    ext = path.suffix.lower()
    if ext in (".gbk", ".gb", ".genbank"):
        return parse_gbk(path)
    elif ext == ".dna":
        return parse_dna(path)
    elif ext in (".fasta", ".fa", ".fna"):
        return parse_fasta(path)
    raise ValueError(f"Unsupported file format: {ext}")


# ═══════════════════════════════════════════════════════════════
#  Write .gbk
# ═══════════════════════════════════════════════════════════════

def write_gbk(project: ProjectData, path: Path) -> None:
    from Bio.Seq import Seq
    from Bio.SeqRecord import SeqRecord
    from Bio.SeqFeature import SeqFeature, SimpleLocation, CompoundLocation

    record = SeqRecord(
        Seq(project.sequence),
        id="geneie", name="geneie", description="Generated by Geneie",
        annotations={"topology": project.topology, "molecule_type": "DNA"},
    )

    record.features.append(SeqFeature(
        SimpleLocation(0, len(project.sequence)),
        type="source",
        qualifiers={"organism": "synthetic construct", "mol_type": "genomic DNA"},
    ))

    # ── user features ──
    for f in project.features:
        if f.segments:
            parts = [SimpleLocation(s["start"], s["end"] + 1, strand=1) for s in f.segments]
            loc = CompoundLocation(parts)
        else:
            loc = SimpleLocation(f.start, f.end + 1, strand=1)

        qual: dict = {"label": [f.name], "geneie_color": [f.color]}
        if f.notes:
            qual["note"] = [f.notes]
        if f.translation:
            qual["translation"] = [f.translation]
        if f.ftype:
            qual["geneie_type"] = [f.ftype]

        record.features.append(SeqFeature(loc, type=f.ftype or "misc_feature", qualifiers=qual))

    # ── primers as native primer_bind features ──
    for p in project.primers:
        import json as _json
        qual = {
            "label": [p.name],
            "geneie_primer_id": [p.id],
            "geneie_primer_type": [p.type],
            "geneie_mismatch_str": [p.mismatch_str],
            "geneie_color": [p.color],
        }
        if p.binding_sites:
            qual["geneie_bindings"] = [_json.dumps(
                [{"s": bs.match_start, "e": bs.match_end, "m": bs.match_str, "t": bs.tm}
                 for bs in p.binding_sites],
                separators=(",", ":"),
            )]
        if p.mismatch_features:
            qual["geneie_mismatch_fs"] = [_json.dumps(
                [{"n": mf.name, "s": mf.start, "e": mf.end} for mf in p.mismatch_features],
                separators=(",", ":"),
            )]

        loc = SimpleLocation(p.match_start, p.match_end + 1, strand=1)
        record.features.append(SeqFeature(loc, type="primer_bind", qualifiers=qual))

    record.annotations["topology"] = project.topology
    record.annotations["molecule_type"] = "DNA"
    path.write_text(record.format("genbank"))


# ═══════════════════════════════════════════════════════════════
#  Helpers
# ═══════════════════════════════════════════════════════════════

def _parse_primer_feature(f) -> Primer:
    qual = f.qualifiers
    loc = f.location
    start = int(loc.start)
    end = int(loc.end) - 1
    import json as _json

    # ── binding sites (new format with Tm) ──
    binding_sites = []
    bs_raw = qual.get("geneie_bindings", [None])[0]
    if bs_raw:
        try:
            bs_data = _json.loads(bs_raw)
            binding_sites = [
                BindingSite(
                    match_start=b["s"], match_end=b["e"],
                    match_str=b["m"], tm=b.get("t", 0.0),
                )
                for b in bs_data
            ]
        except (_json.JSONDecodeError, KeyError):
            pass

    # ── legacy fallback ──
    if not binding_sites:
        leg_str = qual.get("geneie_match_str", [""])[0]
        binding_sites = [BindingSite(
            match_start=start, match_end=end, match_str=leg_str, tm=0.0,
        )]

    # ── mismatch features ──
    mf_raw = qual.get("geneie_mismatch_fs", ["[]"])[0]
    try:
        mf_data = _json.loads(mf_raw)
    except _json.JSONDecodeError:
        mf_data = []
    mfs = [PrimerMismatchFeature(name=m["n"], start=m["s"], end=m["e"]) for m in mf_data]

    return Primer(
        id=qual.get("geneie_primer_id", [qual.get("label", ["unknown"])[0]])[0],
        name=qual.get("label", ["unknown"])[0],
        type=qual.get("geneie_primer_type", ["fwd"])[0],
        mismatch_str=qual.get("geneie_mismatch_str", [""])[0],
        mismatch_features=mfs,
        binding_sites=binding_sites,
        color=qual.get("geneie_color", ["#166534"])[0],
    )


def _default_color(ftype: str) -> str:
    palette = {
        "CDS": "#60A5FA", "promoter": "#34d399", "terminator": "#9ca3af",
        "misc_feature": "#a78bfa", "regulatory": "#fbbf24", "gene": "#f472b6",
        "rep_origin": "#fb923c",
    }
    return palette.get(ftype, "#94a3b8")
